### first stage
FROM node:19-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./


RUN npm install --force

COPY . .


RUN npm run build

### second stage copy to  nginx
FROM nginx:alpine

ARG NGINXFILE

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 3000