version: '3'

services:
  app:
    image: imotechsl/awt-api:${ENV}
    build: ./api
    container_name: awt-api-${ENV}
    restart: unless-stopped
    env_file:
      - ./api/${ENV}.env
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=$MONGO_DOCKER_URI
    #   - API_BASE_URL=$API_BASE_URL
    #   - JWT_ACCESS_TOKEN_SECRET=$JWT_ACCESS_TOKEN_SECRET
    #   - OM_MERCHANT_KEY=$OM_MERCHANT_KEY
    #   - OM_BASIC_AUTH_TOKEN=$OM_BASIC_AUTH_TOKEN
    #   - EMAIL_SENDER=$EMAIL_SENDER
    #   - EMAIL_USERNAME=$EMAIL_USERNAME
    #   - EMAIL_PASSWORD=$EMAIL_PASSWORD
    #   - SENDGRID_API_KEY=$SENDGRID_API_KEY
    #   - JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
    stdin_open: true
    networks:
      - awt-net
    volumes:
      - ./api/:/usr/src/app
      - /usr/src/app/node_modules
    
  awt-web:
    image: imotechsl/awt-web:${ENV}
    container_name: awt-web-${ENV}
    build: ./web
    stdin_open: true
    ports:
      - "4000:3000"
    networks:
      - awt-net
    volumes:
      - ./web/:/usr/src/app
  
  awt-admin:
    depends_on:
      - awt-api
    image: imotechsl/awt-admin:${ENV}
    build: ./client
    stdin_open: true
    container_name: awt-admin-${ENV}
    ports:
      - "3000:3000"
    networks:
      - awt-net
    volumes:
      - ./client/:/usr/src/app
      

  mongodb:
    image: mongo
    container_name: awt-mongo-${ENV}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    networks:
      - awt-net

  nginx:
    build: ./nginx
    image: imotechsl/awt-nginx:${ENV}
    container_name: awt-nginx-${ENV}
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - awt-api
    networks:
      - awt-net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  
  

networks:
 awt-net:
  name: awt-net
  driver: bridge

volumes:
 db:
  name: awt-mongodb
  driver: local